apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gaming

resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/kallangerard/shopping-game
    newTag: sha-fb4fd99@sha256:954570ee62211d58ca431c44273e940c4e8b03c71f3b0b4dd60d5df8254ec243
