apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gaming

resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/kallangerard/shopping-game
    newTag: sha-f3c5f88
