apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gaming

resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/kallangerard/shopping-game
    newTag: sha-84ffe11@sha256:66c718623f73d10ca6bccac8a6063122801bf4fcb45de2cd565c0207d95922a6
