apiVersion: batch/v1
kind: Job
metadata:
  name: shopping-game-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
      containers:
        - name: migrate
          image: ghcr.io/kallangerard/shopping-game:main
          command:
            - python
            - manage.py
            - migrate
            - --noinput
          env:
            - name: DEBUG
              value: "False"
            - name: DATABASE_PATH
              value: /data/db.sqlite3
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: shopping-game-data
