name: CI

on:
  push:
    paths-ignore:
      - manifests/**
      - "*.md"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4

      - name: Run Django tests
        run: nix develop --command sh -c "uv sync --frozen --no-dev && uv run python manage.py test --verbosity=2"
        env:
          DJANGO_SETTINGS_MODULE: shopping_game.settings
